site_name: PSGraph Docs
repo_url: https://github.com/...
theme: readthedocs
pages:
  - Home: index.md
  - PSGraph Basics:
    - What is PSGraph: about.md
    - Quick Start: Quick-Start-Installation-and-Example.md
  - Basic Commands:
  - Examples:
  - Acknowledgements: acknowledgements.md